name: Lint CSS

on:
  - pull_request

jobs:
  lint-css:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.1.0
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Lint CSS
        run: npm run lint:css

